#pragma once

typedef enum {
    VITACOMPANION_PROMOTE_ERROR_NOT_DIRECTORY = -0x7101,
    VITACOMPANION_PROMOTE_ERROR_PATH_TOO_LONG = -0x7102,
    VITACOMPANION_PROMOTE_ERROR_INVALID_LAYOUT = -0x7103,
    VITACOMPANION_PROMOTE_ERROR_INVALID_SFO = -0x7104,
    VITACOMPANION_PROMOTE_ERROR_INVALID_TITLE_ID = -0x7105,
    VITACOMPANION_PROMOTE_ERROR_NO_MEMORY = -0x7106,
    VITACOMPANION_PROMOTE_ERROR_INCOMPLETE_IO = -0x7107
} vitacompanion_promote_error;

int promote_directory(const char *path);
